### ISSUE TITLE
Need assistance in downloading embedded pdf in pdf viewer

### ISSUE THREAD

**Issue by Yvttsplvd** [roboticslab-uc3m/best-practices#49]
Not sure where to post this but I have a subscription for magazines but they are in read online only. No other options. Can someone help isolating the url? Thank you.

**Comment by PeterBowman** [comment]
Hello, @Yvttsplvd. This is a repository devoted to answering questions related to the roboticslab-uc3m organization, its community and projects. I'm afraid this issue is therefore out of topic. Please resort to more generic search aggregators and developer communities such as StackOverflow/Google. Thank you for your understanding.
